// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authorize(arg1) {
  return window['go']['main']['App']['Authorize'](arg1);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function Check() {
  return window['go']['main']['App']['Check']();
}

export function CloseRunningGame() {
  return window['go']['main']['App']['CloseRunningGame']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function Patch() {
  return window['go']['main']['App']['Patch']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function SetAccount(arg1) {
  return window['go']['main']['App']['SetAccount'](arg1);
}

export function SetSkipCinematic(arg1) {
  return window['go']['main']['App']['SetSkipCinematic'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
