// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authorize(arg1:string):Promise<void>;

export function Cancel():Promise<void>;

export function Check():Promise<void>;

export function CloseRunningGame():Promise<void>;

export function GetStatus():Promise<main.LauncherStatus>;

export function IsGameRunning():Promise<boolean>;

export function Patch():Promise<void>;

export function Play():Promise<void>;

export function SetAccount(arg1:string):Promise<main.LauncherStatus>;

export function SetSkipCinematic(arg1:boolean):Promise<void>;

export function SignOut():Promise<void>;
