//go:build windows && frontend

package main

import "embed"

// frontendAssets contains the production bundle generated by pnpm through Wails.
//
//go:embed all:frontend/dist
var frontendAssets embed.FS
