// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authorize(arg1) {
  return window['go']['main']['App']['Authorize'](arg1);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CancelPatch() {
  return window['go']['main']['App']['CancelPatch']();
}

export function Check() {
  return window['go']['main']['App']['Check']();
}

export function CloseDetachedGameInstances() {
  return window['go']['main']['App']['CloseDetachedGameInstances']();
}

export function CloseRunningGame() {
  return window['go']['main']['App']['CloseRunningGame']();
}

export function CloseRunningProfile(arg1) {
  return window['go']['main']['App']['CloseRunningProfile'](arg1);
}

export function CreateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteRemoteProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRemoteProfile'](arg1, arg2, arg3);
}

export function DiscardInterruptedMission(arg1) {
  return window['go']['main']['App']['DiscardInterruptedMission'](arg1);
}

export function GetInstallationStatus() {
  return window['go']['main']['App']['GetInstallationStatus']();
}

export function GetInterruptedMission(arg1) {
  return window['go']['main']['App']['GetInterruptedMission'](arg1);
}

export function GetLauncherIntegrationStatus() {
  return window['go']['main']['App']['GetLauncherIntegrationStatus']();
}

export function GetProfileAvatars() {
  return window['go']['main']['App']['GetProfileAvatars']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRemoteProfiles() {
  return window['go']['main']['App']['GetRemoteProfiles']();
}

export function GetServerConfiguration() {
  return window['go']['main']['App']['GetServerConfiguration']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HasDetachedGameInstances() {
  return window['go']['main']['App']['HasDetachedGameInstances']();
}

export function IsProfileRunning(arg1) {
  return window['go']['main']['App']['IsProfileRunning'](arg1);
}

export function LaunchRemoteProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchRemoteProfile'](arg1, arg2, arg3, arg4);
}

export function LoginRemoteProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoginRemoteProfile'](arg1, arg2, arg3, arg4);
}

export function OpenFirewallSettings() {
  return window['go']['main']['App']['OpenFirewallSettings']();
}

export function OpenReportFolder() {
  return window['go']['main']['App']['OpenReportFolder']();
}

export function OpenSteamDemoInstall() {
  return window['go']['main']['App']['OpenSteamDemoInstall']();
}

export function Patch() {
  return window['go']['main']['App']['Patch']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function RefreshInstallationStatus() {
  return window['go']['main']['App']['RefreshInstallationStatus']();
}

export function RefreshRemoteProfiles() {
  return window['go']['main']['App']['RefreshRemoteProfiles']();
}

export function RegisterRemoteProfile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RegisterRemoteProfile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RelocateToGameRoot(arg1) {
  return window['go']['main']['App']['RelocateToGameRoot'](arg1);
}

export function RemoveLauncherIntegration(arg1) {
  return window['go']['main']['App']['RemoveLauncherIntegration'](arg1);
}

export function RepairLauncherIntegration(arg1) {
  return window['go']['main']['App']['RepairLauncherIntegration'](arg1);
}

export function RestartLauncher() {
  return window['go']['main']['App']['RestartLauncher']();
}

export function ScanRemoteServers(arg1) {
  return window['go']['main']['App']['ScanRemoteServers'](arg1);
}

export function SendReport(arg1, arg2) {
  return window['go']['main']['App']['SendReport'](arg1, arg2);
}

export function SetIdentity(arg1) {
  return window['go']['main']['App']['SetIdentity'](arg1);
}

export function SetServerConfiguration(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetServerConfiguration'](arg1, arg2, arg3, arg4, arg5);
}

export function SetServerPort(arg1) {
  return window['go']['main']['App']['SetServerPort'](arg1);
}

export function SetSkipCinematic(arg1) {
  return window['go']['main']['App']['SetSkipCinematic'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StartDetachedGameInstance(arg1) {
  return window['go']['main']['App']['StartDetachedGameInstance'](arg1);
}

export function UninstallDarkspinner() {
  return window['go']['main']['App']['UninstallDarkspinner']();
}
