// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authorize(arg1:string):Promise<void>;

export function Cancel():Promise<void>;

export function CancelPatch():Promise<void>;

export function Check():Promise<void>;

export function CloseDetachedGameInstances():Promise<void>;

export function CloseRunningGame():Promise<void>;

export function CloseRunningProfile(arg1:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRemoteProfile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DiscardInterruptedMission(arg1:string):Promise<void>;

export function GetInstallationStatus():Promise<main.InstallationStatus>;

export function GetInterruptedMission(arg1:string):Promise<main.InterruptedMission>;

export function GetLauncherIntegrationStatus():Promise<main.LauncherIntegrationStatus>;

export function GetProfileAvatars():Promise<Array<main.ProfileAvatar>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetRemoteProfiles():Promise<Array<main.RemoteProfile>>;

export function GetServerConfiguration():Promise<main.ServerConfiguration>;

export function GetStatus():Promise<main.LauncherStatus>;

export function HasDetachedGameInstances():Promise<boolean>;

export function IsProfileRunning(arg1:string):Promise<boolean>;

export function LaunchRemoteProfile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function LoginRemoteProfile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function OpenFirewallSettings():Promise<void>;

export function OpenReportFolder():Promise<void>;

export function OpenSteamDemoInstall():Promise<void>;

export function Patch():Promise<void>;

export function Play():Promise<void>;

export function RefreshInstallationStatus():Promise<main.InstallationStatus>;

export function RefreshRemoteProfiles():Promise<Array<main.RemoteProfile>>;

export function RegisterRemoteProfile(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean,arg6:boolean):Promise<void>;

export function RelocateToGameRoot(arg1:main.RelocationRequest):Promise<void>;

export function RemoveLauncherIntegration(arg1:string):Promise<main.LauncherIntegrationStatus>;

export function RepairLauncherIntegration(arg1:string):Promise<main.LauncherIntegrationStatus>;

export function RestartLauncher():Promise<void>;

export function ScanRemoteServers(arg1:string):Promise<Array<main.RemoteServer>>;

export function SendReport(arg1:string,arg2:string):Promise<main.ReportResult>;

export function SetIdentity(arg1:string):Promise<main.LauncherStatus>;

export function SetServerConfiguration(arg1:number,arg2:boolean,arg3:string,arg4:string):Promise<main.ServerConfiguration>;

export function SetServerPort(arg1:number):Promise<main.ServerConfiguration>;

export function SetSkipCinematic(arg1:boolean):Promise<void>;

export function SignOut():Promise<void>;

export function StartDetachedGameInstance(arg1:string):Promise<void>;

export function UninstallDarkspinner():Promise<void>;
